#!/usr/bin/env python3
"""Generate an FCEUX Lua capture script from a trace-sms buttons script.

The Lua script replays the acceptance route on the real NES ROM inside FCEUX
and dumps gd-format screenshots at state-keyed trigger points, so the frames
line up with trace-sms checkpoint dumps regardless of power-on frame offset.

Sync model: the buttons schedule is authored on the trace-sms frame counter.
We anchor on the OperMode ($0770) 0->1 transition: trace-sms sees it at frame
ANCHOR_TRACE; when FCEUX sees it at frame f1, every schedule event at frame
F >= GAMEPLAY_SCHED_START is replayed at F + (f1 - ANCHOR_TRACE). Camera
triggers fire on exact ScreenLeft page:x match, frame-independent.

Usage: gen_capture_lua.py <buttons-file> <out.lua> <capture-dir>
"""
import sys

# trace-sms frame where OperMode 0->1 was observed (SMS_WATCH_ADDR=C770).
ANCHOR_TRACE = 103
# Schedule events at/after this frame are gameplay-relative and get shifted.
GAMEPLAY_SCHED_START = 220

BUTTON_MAP = {
    "a": "A", "b": "B", "start": "start", "select": "select",
    "up": "up", "down": "down", "left": "left", "right": "right",
}

# name -> trigger. ("frame", n) fires at absolute movie frame n (pre-anchor),
# ("anchor", d) fires at f1 + d, ("cam", page, x) on ScreenLeft match.
CAPTURES = [
    ("title-before-start", ("frame", 60)),
    ("gameplay-start", ("anchor", 220 - ANCHOR_TRACE)),
    ("early-1-1", ("cam", 0x01, 0xE2)),
    ("mid-1-1", ("cam", 0x06, 0x78)),
    ("late-1-1", ("cam", 0x0A, 0xA9)),
    ("flagpole", ("cam", 0x0C, 0x26)),
    ("post-transition-1-2", ("anchor", 4450 - ANCHOR_TRACE)),
]


def parse_buttons(path):
    events = []
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        frame_s, btns = line.split(":", 1)
        held = [BUTTON_MAP[b.strip()] for b in btns.split(",") if b.strip()]
        events.append((int(frame_s), held))
    events.sort()
    return events


def main():
    buttons_path, out_path, capdir = sys.argv[1], sys.argv[2], sys.argv[3]
    events = parse_buttons(buttons_path)

    ev_lines = []
    for frame, held in events:
        flags = ", ".join(f'{b}=true' for b in held)
        shifted = "true" if frame >= GAMEPLAY_SCHED_START else "false"
        ev_lines.append(f"  {{f={frame}, shifted={shifted}, pad={{{flags}}}}},")

    cap_lines = []
    for name, trig in CAPTURES:
        if trig[0] == "frame":
            cap_lines.append(f'  {{name="{name}", kind="frame", f={trig[1]}}},')
        elif trig[0] == "anchor":
            cap_lines.append(f'  {{name="{name}", kind="anchor", d={trig[1]}}},')
        else:
            cap_lines.append(
                f'  {{name="{name}", kind="cam", page={trig[1]}, x={trig[2]}}},')

    lua = f"""-- Generated by scripts/nesref/gen_capture_lua.py. Do not edit.
local CAPDIR = "{capdir}"
local ANCHOR_TRACE = {ANCHOR_TRACE}

local events = {{
{chr(10).join(ev_lines)}
}}

local captures = {{
{chr(10).join(cap_lines)}
}}

emu.speedmode("maximum")

local f1 = nil          -- FCEUX frame of OperMode 0->1
local delta = 0
local ev_idx = 1
local pad = {{}}
local done = 0
local log = io.open(CAPDIR .. "/capture.log", "w")

local function snap(name)
  local gd = gui.gdscreenshot()
  local fh = io.open(CAPDIR .. "/" .. name .. ".gd", "wb")
  fh:write(gd)
  fh:close()
  log:write(string.format("capture %s frame=%d\\n", name, emu.framecount()))
  log:flush()
  done = done + 1
end

local prev_opermode = memory.readbyte(0x0770)

while true do
  local frame = emu.framecount()

  -- Advance the input schedule. Events authored at frame >= {GAMEPLAY_SCHED_START}
  -- replay at f + delta once the anchor is known.
  while ev_idx <= #events do
    local ev = events[ev_idx]
    local due = ev.f
    if ev.shifted then due = due + delta end
    if frame >= due then
      pad = ev.pad
      ev_idx = ev_idx + 1
    else
      break
    end
  end
  joypad.set(1, pad)

  local opermode = memory.readbyte(0x0770)
  if f1 == nil and prev_opermode == 0 and opermode == 1 then
    f1 = frame
    delta = f1 - ANCHOR_TRACE
    log:write(string.format("anchor f1=%d delta=%d\\n", f1, delta))
    log:flush()
  end
  prev_opermode = opermode

  local page = memory.readbyte(0x071A)
  local camx = memory.readbyte(0x071C)
  for _, c in ipairs(captures) do
    if not c.hit then
      if c.kind == "frame" and frame == c.f then
        c.hit = true; snap(c.name)
      elseif c.kind == "anchor" and f1 ~= nil and frame == f1 + c.d then
        c.hit = true; snap(c.name)
      elseif c.kind == "cam" and f1 ~= nil and page == c.page and camx == c.x then
        c.hit = true; snap(c.name)
      end
    end
  end

  if done >= #captures then
    log:write("all captures done\\n")
    log:close()
    os.exit(0)
  end
  emu.frameadvance()
end
"""
    with open(out_path, "w") as f:
        f.write(lua)
    print(f"wrote {out_path}: {len(events)} input events, {len(CAPTURES)} captures")


if __name__ == "__main__":
    main()
