[package]
name = "validation"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
cpu6502 = { workspace = true }
ir = { workspace = true }
lower = { workspace = true }
oracle_6502 = { workspace = true }
z80_emit = { workspace = true }
z80_emu = { workspace = true }
profile = { workspace = true }
