use std::collections::HashMap;
use std::io;

#[derive(Debug)]
struct Patch {
    offset: usize,
    label: String,
}

#[derive(Debug)]
pub struct Z80Output {
    pub bytes: Vec<u8>,
    pub asm: String,
}

#[derive(Debug)]
pub struct Z80Program {
    bytes: Vec<u8>,
    asm: Vec<String>,
    labels: HashMap<String, u16>,
    patches: Vec<Patch>,
    fresh_id: usize,
}

impl Z80Program {
    pub fn new() -> Self {
        let mut program = Self {
            bytes: Vec::new(),
            asm: Vec::new(),
            labels: HashMap::new(),
            patches: Vec::new(),
            fresh_id: 0,
        };
        program.asm.push("; Generated by poc z80_backend.".into());
        program
            .asm
            .push("; Origin is SMS ROM address $0000.".into());
        program.asm.push(".org $0000".into());
        program
    }

    pub fn position(&self) -> u16 {
        self.bytes.len() as u16
    }

    pub fn comment(&mut self, text: impl AsRef<str>) {
        self.asm.push(format!("; {}", text.as_ref()));
    }

    pub fn label(&mut self, name: impl AsRef<str>) {
        let name = name.as_ref();
        self.labels.insert(name.to_string(), self.position());
        self.asm.push(format!("{name}:"));
    }

    pub fn fresh_label(&mut self, prefix: &str) -> String {
        let label = format!("{prefix}_{:04}", self.fresh_id);
        self.fresh_id += 1;
        label
    }

    pub fn align(&mut self, align: usize) {
        if align == 0 {
            return;
        }
        if !self.bytes.len().is_multiple_of(align) {
            self.asm.push(format!("    ; align {align}"));
        }
        while !self.bytes.len().is_multiple_of(align) {
            self.byte(0x00, None);
        }
    }

    pub fn data(&mut self, label: &str, bytes: &[u8]) {
        self.label(label);
        for chunk in bytes.chunks(16) {
            let values = chunk
                .iter()
                .map(|byte| format!("${byte:02X}"))
                .collect::<Vec<_>>()
                .join(", ");
            self.asm.push(format!("    .db {values}"));
            self.bytes.extend_from_slice(chunk);
        }
    }

    pub fn finish(mut self) -> io::Result<Z80Output> {
        for patch in &self.patches {
            let value = *self.labels.get(&patch.label).ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("unresolved Z80 label `{}`", patch.label),
                )
            })?;
            let [lo, hi] = value.to_le_bytes();
            self.bytes[patch.offset] = lo;
            self.bytes[patch.offset + 1] = hi;
        }

        self.asm.push(String::new());
        self.asm
            .push("; SMS header/checksum is applied by the Rust ROM packer.".into());
        Ok(Z80Output {
            bytes: self.bytes,
            asm: self.asm.join("\n"),
        })
    }

    pub fn di(&mut self) {
        self.byte(0xF3, Some("di"));
    }

    pub fn ret(&mut self) {
        self.byte(0xC9, Some("ret"));
    }

    pub fn cpl(&mut self) {
        self.byte(0x2F, Some("cpl"));
    }

    pub fn or_a(&mut self) {
        self.byte(0xB7, Some("or a"));
    }

    pub fn ld_b_a(&mut self) {
        self.byte(0x47, Some("ld b,a"));
    }

    pub fn ld_c_a(&mut self) {
        self.byte(0x4F, Some("ld c,a"));
    }

    pub fn ld_a_b(&mut self) {
        self.byte(0x78, Some("ld a,b"));
    }

    pub fn ld_a_c(&mut self) {
        self.byte(0x79, Some("ld a,c"));
    }

    pub fn ld_a_hl_ptr(&mut self) {
        self.byte(0x7E, Some("ld a,(hl)"));
    }

    pub fn inc_hl(&mut self) {
        self.byte(0x23, Some("inc hl"));
    }

    pub fn dec_bc(&mut self) {
        self.byte(0x0B, Some("dec bc"));
    }

    pub fn or_c(&mut self) {
        self.byte(0xB1, Some("or c"));
    }

    pub fn and_b(&mut self) {
        self.byte(0xA0, Some("and b"));
    }

    pub fn and_a(&mut self) {
        self.byte(0xA7, Some("and a"));
    }

    pub fn ld_sp_imm(&mut self, value: u16) {
        self.byte(0x31, None);
        self.word(value);
        self.asm.push(format!("    ld sp,${value:04X}"));
    }

    pub fn ld_hl_label(&mut self, label: &str) {
        self.byte(0x21, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    ld hl,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn ld_bc_imm(&mut self, value: u16) {
        self.byte(0x01, None);
        self.word(value);
        self.asm.push(format!("    ld bc,${value:04X}"));
    }

    pub fn ld_a_imm(&mut self, value: u8) {
        self.byte(0x3E, None);
        self.byte(value, None);
        self.asm.push(format!("    ld a,${value:02X}"));
    }

    pub fn ld_a_abs(&mut self, addr: u16) {
        self.byte(0x3A, None);
        self.word(addr);
        self.asm.push(format!("    ld a,(${addr:04X})"));
    }

    pub fn ld_abs_a(&mut self, addr: u16) {
        self.byte(0x32, None);
        self.word(addr);
        self.asm.push(format!("    ld (${addr:04X}),a"));
    }

    pub fn in_a(&mut self, port: u8) {
        self.byte(0xDB, None);
        self.byte(port, None);
        self.asm.push(format!("    in a,(${port:02X})"));
    }

    pub fn out_a(&mut self, port: u8) {
        self.byte(0xD3, None);
        self.byte(port, None);
        self.asm.push(format!("    out (${port:02X}),a"));
    }

    pub fn and_imm(&mut self, value: u8) {
        self.byte(0xE6, None);
        self.byte(value, None);
        self.asm.push(format!("    and ${value:02X}"));
    }

    pub fn xor_imm(&mut self, value: u8) {
        self.byte(0xEE, None);
        self.byte(value, None);
        self.asm.push(format!("    xor ${value:02X}"));
    }

    pub fn add_a_imm(&mut self, value: u8) {
        self.byte(0xC6, None);
        self.byte(value, None);
        self.asm.push(format!("    add a,${value:02X}"));
    }

    pub fn adc_a_imm(&mut self, value: u8) {
        self.byte(0xCE, None);
        self.byte(value, None);
        self.asm.push(format!("    adc a,${value:02X}"));
    }

    pub fn cp_imm(&mut self, value: u8) {
        self.byte(0xFE, None);
        self.byte(value, None);
        self.asm.push(format!("    cp ${value:02X}"));
    }

    pub fn call(&mut self, label: &str) {
        self.byte(0xCD, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    call {label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn call_nz(&mut self, label: &str) {
        self.byte(0xC4, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    call nz,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn jp(&mut self, label: &str) {
        self.byte(0xC3, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    jp {label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn jp_z(&mut self, label: &str) {
        self.byte(0xCA, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    jp z,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn jp_nz(&mut self, label: &str) {
        self.byte(0xC2, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    jp nz,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn jp_c(&mut self, label: &str) {
        self.byte(0xDA, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    jp c,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    pub fn jp_nc(&mut self, label: &str) {
        self.byte(0xD2, None);
        let patch = self.word_patch(label);
        self.asm.push(format!("    jp nc,{label}"));
        self.patches.push(Patch {
            offset: patch,
            label: label.to_string(),
        });
    }

    fn word_patch(&mut self, _label: &str) -> usize {
        let patch = self.bytes.len();
        self.word(0);
        patch
    }

    fn byte(&mut self, value: u8, asm: Option<&str>) {
        self.bytes.push(value);
        if let Some(asm) = asm {
            self.asm.push(format!("    {asm}"));
        }
    }

    fn word(&mut self, value: u16) {
        self.bytes.extend_from_slice(&value.to_le_bytes());
    }
}
